export const taskTypes = {
    CREATE_TASK: 'CREATE_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    CREATE_TASKS_LIST: 'CREATE_TASKS_LIST',
    CLEAR_TASKS_LIST: 'CLEAR_TASKS_LIST',
    FIND_TASK_DETAILS: 'FIND_TASK_DETAILS',
    SET_TASK_DETAILS: 'SET_TASK_DETAILS',
    CLEAR_TASK_DETAILS: 'CLEAR_TASK_DETAILS',
};

export const timerTypes = {
    START_TIMER: 'START_TIMER',
    UPDATE_NAME: 'UPDATE_NAME',
    STOP_TIMER: 'STOP_TIMER',
};

export default {
    taskTypes,
    timerTypes,
};